### ISSUE TITLE
segmentation.py: How to find the "from .model import Segmentor  # final_my_unet"

### ISSUE THREAD

**Issue by LiXiaoli921** [yu02019/MouseGAN-pp#4]
the code as follow:
`from .model import Segmentor  # final_my_unet` of the second line, 
how to get the model? Thanks

**Comment by yu02019** [comment]
Thank you for reaching out with your issue. 
the Segmentor class is indeed defined in the : 
https://github.com/yu02019/MouseGAN-pp/blob/3c521679c320cfce619ef636e6d89c69b665b469/segmentation/model.py#L27

If you're encountering an issue with importing Segmentor, it's likely due to the current working directory not being set correctly, which prevents Python from locating the module. You can usd 'cd' to change your working directory. Additionally, if you are working within an IDE (like PyCharm), please make sure your project settings are configured correctly so that the segmentation directory is recognized as a source directory.

I hope these suggestions help resolve your issue. If there are any further questions or another issue arises, please feel free to ask for more clarification.
